In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv("Activity_User.csv")

In [3]:
df1=df.copy()

In [29]:
df1.head()

,view_id,user_id,show_id,duration_watched,watch_date,completion_percentage
0,V000001,U01725,S0589,192.0,2024-01-02,62.0
1,V000002,U01956,S0161,500.0,2024-07-11,31.0
2,V000003,U00491,S0379,500.0,2025-12-06,28.0
3,V000004,U01384,S0710,161.0,2024-03-08,15.0
4,V000005,U01257,S0920,25.0,2024-03-14,30.0

In [4]:
df1.shape

(20000, 6)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   view_id                20000 non-null  object
 1   user_id                20000 non-null  object
 2   show_id                20000 non-null  object
 3   duration_watched       20000 non-null  float64
 4   watch_date             20000 non-null  object
 5   completion_percentage  20000 non-null  float64
dtypes: float64(2), object(4)
memory usage: 937.6+ KB

In [6]:
df1.isnull().sum()

view_id                  0
user_id                  0
show_id                  0
duration_watched         0
watch_date               0
completion_percentage    0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(0)

In [25]:
df1[df1.duplicated()]

Empty DataFrame
Columns: [view_id, user_id, show_id, duration_watched, watch_date, completion_percentage]
Index: []

In [11]:
df2=pd.read_csv('Movies_clean.csv')

In [12]:
df3=df2.copy()

In [28]:
df3.head()

,show_id,title,genre,language,release_year,content_type,season,episode
0,S0001,Pushpa,Drama,Telugu,2021,Series,1,3
1,S0002,Hi Nanna,Thriller,Tamil,2025,Movie,1,1
2,S0003,Master,Action,Telugu,2024,Movie,1,1
3,S0004,Good Night,Action,Telugu,2019,Movie,1,1
4,S0005,Master,Action,Telugu,2022,Movie,1,1

In [14]:
df3.shape

(1000, 8)

In [15]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1000 non-null   object
 1   title         1000 non-null   object
 2   genre         1000 non-null   object
 3   language      1000 non-null   object
 4   release_year  1000 non-null   int64
 5   content_type  1000 non-null   object
 6   season        1000 non-null   int64
 7   episode       1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [16]:
df3.isnull().sum()

show_id         0
title           0
genre           0
language        0
release_year    0
content_type    0
season          0
episode         0
dtype: int64

In [17]:
df3.duplicated().sum()

np.int64(0)

In [26]:
df3[df3.duplicated()]

Empty DataFrame
Columns: [show_id, title, genre, language, release_year, content_type, season, episode]
Index: []

In [18]:
df4=pd.read_csv('Users_clean.csv')

In [19]:
df5=df4.copy()

In [27]:
df5.head()

,user_id,join_date,plan_type,subscription_status,cancel_date,last_login_date
0,U00001,2024-05-18,Premimum,Active,---,2025-05-10
1,U00002,2024-06-13,Standard,Active,---,2024-06-20
2,U00003,2023-04-06,Basic,Active,---,2023-08-22
3,U00004,2024-09-27,Standard,Cancelled,2025-09-03,2024-09-30
4,U00005,2024-12-20,Standard,Cancelled,2025-11-10,2025-09-15

In [20]:
df5.shape

(2000, 6)

In [21]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              2000 non-null   object
 1   join_date            2000 non-null   object
 2   plan_type            2000 non-null   object
 3   subscription_status  2000 non-null   object
 4   cancel_date          2000 non-null   object
 5   last_login_date      2000 non-null   object
dtypes: object(6)
memory usage: 93.9+ KB

In [22]:
df5.isnull().sum()

user_id                0
join_date              0
plan_type              0
subscription_status    0
cancel_date            0
last_login_date        0
dtype: int64

In [23]:
df5.duplicated().sum()

np.int64(0)

In [24]:
df5[df5.duplicated()]

Empty DataFrame
Columns: [user_id, join_date, plan_type, subscription_status, cancel_date, last_login_date]
Index: []